FROM node:22-alpine AS builder
WORKDIR /app
COPY package*.json ./
RUN npm install
COPY . .
RUN npx esbuild src/index.ts --bundle --platform=node --outdir=dist/worker --external:@prisma/client --external:sqlite3

FROM node:22-alpine
WORKDIR /app
COPY package*.json ./
RUN npm install --production
COPY --from=builder /app/dist/worker ./dist/worker
COPY --from=builder /app/prisma ./prisma
RUN npx prisma generate
# Role worker
ENV ROLE=worker
CMD ["node", "dist/worker/index.js"]
